# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'key1.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(842, 513)
        Dialog.setWhatsThis("")
        Dialog.setStyleSheet("background-color:rgb(32, 74, 135);")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(0, 20, 41, 51))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    \n"
"border:none;\n"
"border-radius:8px;\n"
"background-color: rgb(46, 52, 54);\n"
"color:rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed {\n"
"    \n"
"    \n"
"    border:5px\n"
"}\n"
"QPushButton:hover{\n"
"   background-color: rgb(245, 121, 0);\n"
"    color:rgb(255, 255, 255);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(40, 20, 51, 51))
        self.pushButton_2.setStyleSheet("QPushButton{border:none;border-radius:8px;background-color: rgb(46, 52, 54);color:rgb(255, 255, 255);}QPushButton:pressed {border:5px}QPushButton:hover{background-color: rgb(245, 121, 0);color:rgb(255, 255, 255);}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(90, 20, 51, 51))
        self.pushButton_3.setStyleSheet("QPushButton{border:none;border-radius:8px;background-color: rgb(46, 52, 54);color:rgb(255, 255, 255);}QPushButton:pressed {border:5px}QPushButton:hover{background-color: rgb(245, 121, 0);color:rgb(255, 255, 255);}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(140, 20, 51, 51))
        self.pushButton_4.setStyleSheet("QPushButton{border:none;border-radius:8px;background-color: rgb(46, 52, 54);color:rgb(255, 255, 255);}QPushButton:pressed {border:5px}QPushButton:hover{background-color: rgb(245, 121, 0);color:rgb(255, 255, 255);}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(Dialog)
        self.pushButton_5.setGeometry(QtCore.QRect(190, 20, 51, 51))
        self.pushButton_5.setStyleSheet("QPushButton{border:none;border-radius:8px;background-color: rgb(46, 52, 54);color:rgb(255, 255, 255);}QPushButton:pressed {border:5px}QPushButton:hover{background-color: rgb(245, 121, 0);color:rgb(255, 255, 255);}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(Dialog)
        self.pushButton_6.setGeometry(QtCore.QRect(240, 20, 51, 51))
        self.pushButton_6.setStyleSheet("QPushButton{border:none;border-radius:8px;background-color: rgb(46, 52, 54);color:rgb(255, 255, 255);}QPushButton:pressed {border:5px}QPushButton:hover{background-color: rgb(245, 121, 0);color:rgb(255, 255, 255);}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(Dialog)
        self.pushButton_7.setGeometry(QtCore.QRect(290, 20, 51, 51))
        self.pushButton_7.setStyleSheet("QPushButton{border:none;border-radius:8px;background-color: rgb(46, 52, 54);color:rgb(255, 255, 255);}QPushButton:pressed {border:5px}QPushButton:hover{background-color: rgb(245, 121, 0);color:rgb(255, 255, 255);}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(Dialog)
        self.pushButton_8.setGeometry(QtCore.QRect(340, 20, 51, 51))
        self.pushButton_8.setStyleSheet("QPushButton{border:none;border-radius:8px;background-color: rgb(46, 52, 54);color:rgb(255, 255, 255);}QPushButton:pressed {border:5px}QPushButton:hover{background-color: rgb(245, 121, 0);color:rgb(255, 255, 255);}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(Dialog)
        self.pushButton_9.setGeometry(QtCore.QRect(390, 20, 51, 51))
        self.pushButton_9.setStyleSheet("QPushButton{border:none;border-radius:8px;background-color: rgb(46, 52, 54);color:rgb(255, 255, 255);}QPushButton:pressed {border:5px}QPushButton:hover{background-color: rgb(245, 121, 0);color:rgb(255, 255, 255);}")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(Dialog)
        self.pushButton_10.setGeometry(QtCore.QRect(440, 20, 51, 51))
        self.pushButton_10.setStyleSheet("QPushButton{border:none;border-radius:8px;background-color: rgb(46, 52, 54);color:rgb(255, 255, 255);}QPushButton:pressed {border:5px}QPushButton:hover{background-color: rgb(245, 121, 0);color:rgb(255, 255, 255);}")
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(Dialog)
        self.pushButton_11.setGeometry(QtCore.QRect(490, 20, 51, 51))
        self.pushButton_11.setStyleSheet("QPushButton{border:none;border-radius:8px;background-color: rgb(46, 52, 54);color:rgb(255, 255, 255);}QPushButton:pressed {border:5px}QPushButton:hover{background-color: rgb(245, 121, 0);color:rgb(255, 255, 255);}")
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(Dialog)
        self.pushButton_12.setGeometry(QtCore.QRect(540, 20, 51, 51))
        self.pushButton_12.setStyleSheet("QPushButton{border:none;border-radius:8px;background-color: rgb(46, 52, 54);color:rgb(255, 255, 255);}QPushButton:pressed {border:5px}QPushButton:hover{background-color: rgb(245, 121, 0);color:rgb(255, 255, 255);}")
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(Dialog)
        self.pushButton_13.setGeometry(QtCore.QRect(590, 20, 51, 51))
        self.pushButton_13.setStyleSheet("QPushButton{border:none;border-radius:8px;background-color: rgb(46, 52, 54);color:rgb(255, 255, 255);}QPushButton:pressed {border:5px}QPushButton:hover{background-color: rgb(245, 121, 0);color:rgb(255, 255, 255);}")
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(Dialog)
        self.pushButton_14.setGeometry(QtCore.QRect(640, 20, 51, 51))
        self.pushButton_14.setStyleSheet("QPushButton{border:none;border-radius:8px;background-color: rgb(46, 52, 54);color:rgb(255, 255, 255);}QPushButton:pressed {border:5px}QPushButton:hover{background-color: rgb(245, 121, 0);color:rgb(255, 255, 255);}")
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(Dialog)
        self.pushButton_15.setGeometry(QtCore.QRect(690, 20, 51, 51))
        self.pushButton_15.setStyleSheet("QPushButton{border:none;border-radius:8px;background-color: rgb(46, 52, 54);color:rgb(255, 255, 255);}QPushButton:pressed {border:5px}QPushButton:hover{background-color: rgb(245, 121, 0);color:rgb(255, 255, 255);}")
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(Dialog)
        self.pushButton_16.setGeometry(QtCore.QRect(740, 20, 61, 51))
        self.pushButton_16.setStyleSheet("QPushButton{border:none;border-radius:8px;background-color: rgb(46, 52, 54);color:rgb(255, 255, 255);}QPushButton:pressed {border:5px}QPushButton:hover{background-color: rgb(245, 121, 0);color:rgb(255, 255, 255);}")
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_17 = QtWidgets.QPushButton(Dialog)
        self.pushButton_17.setGeometry(QtCore.QRect(0, 70, 50, 61))
        self.pushButton_17.setStyleSheet("QPushButton{border:none;border-radius:8px;background-color: rgb(46, 52, 54);color:rgb(255, 255, 255);}QPushButton:pressed {border:5px}QPushButton:hover{background-color: rgb(245, 121, 0);color:rgb(255, 255, 255);}")
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtWidgets.QPushButton(Dialog)
        self.pushButton_18.setGeometry(QtCore.QRect(40, 70, 51, 61))
        self.pushButton_18.setStyleSheet("QPushButton{border:none;border-radius:8px;background-color: rgb(46, 52, 54);color:rgb(255, 255, 255);}QPushButton:pressed {border:5px}QPushButton:hover{background-color: rgb(245, 121, 0);color:rgb(255, 255, 255);}")
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_19 = QtWidgets.QPushButton(Dialog)
        self.pushButton_19.setGeometry(QtCore.QRect(90, 70, 51, 61))
        self.pushButton_19.setStyleSheet("QPushButton{border:none;border-radius:8px;background-color: rgb(46, 52, 54);color:rgb(255, 255, 255);}QPushButton:pressed {border:5px}QPushButton:hover{background-color: rgb(245, 121, 0);color:rgb(255, 255, 255);}")
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_20 = QtWidgets.QPushButton(Dialog)
        self.pushButton_20.setGeometry(QtCore.QRect(140, 70, 51, 61))
        self.pushButton_20.setStyleSheet("QPushButton{border:none;border-radius:8px;background-color: rgb(46, 52, 54);color:rgb(255, 255, 255);}QPushButton:pressed {border:5px}QPushButton:hover{background-color: rgb(245, 121, 0);color:rgb(255, 255, 255);}")
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_21 = QtWidgets.QPushButton(Dialog)
        self.pushButton_21.setGeometry(QtCore.QRect(190, 70, 51, 61))
        self.pushButton_21.setStyleSheet("QPushButton{border:none;border-radius:8px;background-color: rgb(46, 52, 54);color:rgb(255, 255, 255);}QPushButton:pressed {border:5px}QPushButton:hover{background-color: rgb(245, 121, 0);color:rgb(255, 255, 255);}")
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_22 = QtWidgets.QPushButton(Dialog)
        self.pushButton_22.setGeometry(QtCore.QRect(240, 70, 51, 61))
        self.pushButton_22.setStyleSheet("QPushButton{border:none;border-radius:8px;background-color: rgb(46, 52, 54);color:rgb(255, 255, 255);}QPushButton:pressed {border:5px}QPushButton:hover{background-color: rgb(245, 121, 0);color:rgb(255, 255, 255);}")
        self.pushButton_22.setObjectName("pushButton_22")
        self.pushButton_23 = QtWidgets.QPushButton(Dialog)
        self.pushButton_23.setGeometry(QtCore.QRect(290, 70, 51, 61))
        self.pushButton_23.setStyleSheet("QPushButton{border:none;border-radius:8px;background-color: rgb(46, 52, 54);color:rgb(255, 255, 255);}QPushButton:pressed {border:5px}QPushButton:hover{background-color: rgb(245, 121, 0);color:rgb(255, 255, 255);}")
        self.pushButton_23.setObjectName("pushButton_23")
        self.pushButton_24 = QtWidgets.QPushButton(Dialog)
        self.pushButton_24.setGeometry(QtCore.QRect(340, 70, 51, 61))
        self.pushButton_24.setStyleSheet("QPushButton{border:none;border-radius:8px;background-color: rgb(46, 52, 54);color:rgb(255, 255, 255);}QPushButton:pressed {border:5px}QPushButton:hover{background-color: rgb(245, 121, 0);color:rgb(255, 255, 255);}")
        self.pushButton_24.setObjectName("pushButton_24")
        self.pushButton_25 = QtWidgets.QPushButton(Dialog)
        self.pushButton_25.setGeometry(QtCore.QRect(390, 70, 51, 61))
        self.pushButton_25.setStyleSheet("QPushButton{border:none;border-radius:8px;background-color: rgb(46, 52, 54);color:rgb(255, 255, 255);}QPushButton:pressed {border:5px}QPushButton:hover{background-color: rgb(245, 121, 0);color:rgb(255, 255, 255);}")
        self.pushButton_25.setObjectName("pushButton_25")
        self.pushButton_26 = QtWidgets.QPushButton(Dialog)
        self.pushButton_26.setGeometry(QtCore.QRect(440, 70, 51, 61))
        self.pushButton_26.setStyleSheet("QPushButton{border:none;border-radius:8px;background-color: rgb(46, 52, 54);color:rgb(255, 255, 255);}QPushButton:pressed {border:5px}QPushButton:hover{background-color: rgb(245, 121, 0);color:rgb(255, 255, 255);}")
        self.pushButton_26.setObjectName("pushButton_26")
        self.pushButton_27 = QtWidgets.QPushButton(Dialog)
        self.pushButton_27.setGeometry(QtCore.QRect(490, 70, 51, 61))
        self.pushButton_27.setStyleSheet("QPushButton{border:none;border-radius:8px;background-color: rgb(46, 52, 54);color:rgb(255, 255, 255);}QPushButton:pressed {border:5px}QPushButton:hover{background-color: rgb(245, 121, 0);color:rgb(255, 255, 255);}")
        self.pushButton_27.setObjectName("pushButton_27")
        self.pushButton_28 = QtWidgets.QPushButton(Dialog)
        self.pushButton_28.setGeometry(QtCore.QRect(540, 70, 51, 61))
        self.pushButton_28.setStyleSheet("QPushButton{border:none;border-radius:8px;background-color: rgb(46, 52, 54);color:rgb(255, 255, 255);}QPushButton:pressed {border:5px}QPushButton:hover{background-color: rgb(245, 121, 0);color:rgb(255, 255, 255);}")
        self.pushButton_28.setObjectName("pushButton_28")
        self.pushButton_29 = QtWidgets.QPushButton(Dialog)
        self.pushButton_29.setGeometry(QtCore.QRect(590, 70, 51, 61))
        self.pushButton_29.setStyleSheet("QPushButton{border:none;border-radius:8px;background-color: rgb(46, 52, 54);color:rgb(255, 255, 255);}QPushButton:pressed {border:5px}QPushButton:hover{background-color: rgb(245, 121, 0);color:rgb(255, 255, 255);}")
        self.pushButton_29.setObjectName("pushButton_29")
        self.pushButton_30 = QtWidgets.QPushButton(Dialog)
        self.pushButton_30.setGeometry(QtCore.QRect(640, 70, 51, 61))
        self.pushButton_30.setStyleSheet("QPushButton{border:none;border-radius:8px;background-color: rgb(46, 52, 54);color:rgb(255, 255, 255);}QPushButton:pressed {border:5px}QPushButton:hover{background-color: rgb(245, 121, 0);color:rgb(255, 255, 255);}")
        self.pushButton_30.setObjectName("pushButton_30")
        self.pushButton_31 = QtWidgets.QPushButton(Dialog)
        self.pushButton_31.setGeometry(QtCore.QRect(690, 70, 51, 61))
        self.pushButton_31.setStyleSheet("QPushButton{border:none;border-radius:8px;background-color: rgb(46, 52, 54);color:rgb(255, 255, 255);}QPushButton:pressed {border:5px}QPushButton:hover{background-color: rgb(245, 121, 0);color:rgb(255, 255, 255);}")
        self.pushButton_31.setObjectName("pushButton_31")
        self.pushButton_32 = QtWidgets.QPushButton(Dialog)
        self.pushButton_32.setGeometry(QtCore.QRect(740, 70, 61, 61))
        self.pushButton_32.setStyleSheet("QPushButton{border:none;border-radius:8px;background-color: rgb(46, 52, 54);color:rgb(255, 255, 255);}QPushButton:pressed {border:5px}QPushButton:hover{background-color: rgb(245, 121, 0);color:rgb(255, 255, 255);}")
        self.pushButton_32.setObjectName("pushButton_32")
        self.pushButton_33 = QtWidgets.QPushButton(Dialog)
        self.pushButton_33.setGeometry(QtCore.QRect(800, 70, 41, 121))
        self.pushButton_33.setStyleSheet("QPushButton{border:none;border-radius:8px;background-color: rgb(46, 52, 54);color:rgb(255, 255, 255);}QPushButton:pressed {border:5px}QPushButton:hover{background-color: rgb(245, 121, 0);color:rgb(255, 255, 255);}")
        self.pushButton_33.setObjectName("pushButton_33")
        self.pushButton_102 = QtWidgets.QPushButton(Dialog)
        self.pushButton_102.setGeometry(QtCore.QRect(340, 130, 51, 61))
        self.pushButton_102.setStyleSheet("QPushButton{border:none;border-radius:8px;background-color: rgb(46, 52, 54);color:rgb(255, 255, 255);}QPushButton:pressed {border:5px}QPushButton:hover{background-color: rgb(245, 121, 0);color:rgb(255, 255, 255);}")
        self.pushButton_102.setObjectName("pushButton_102")
        self.pushButton_89 = QtWidgets.QPushButton(Dialog)
        self.pushButton_89.setGeometry(QtCore.QRect(490, 130, 51, 61))
        self.pushButton_89.setStyleSheet("QPushButton{border:none;border-radius:8px;background-color: rgb(46, 52, 54);color:rgb(255, 255, 255);}QPushButton:pressed {border:5px}QPushButton:hover{background-color: rgb(245, 121, 0);color:rgb(255, 255, 255);}")
        self.pushButton_89.setObjectName("pushButton_89")
        self.pushButton_95 = QtWidgets.QPushButton(Dialog)
        self.pushButton_95.setGeometry(QtCore.QRect(0, 130, 50, 61))
        self.pushButton_95.setStyleSheet("QPushButton{border:none;border-radius:8px;background-color: rgb(46, 52, 54);color:rgb(255, 255, 255);}QPushButton:pressed {border:5px}QPushButton:hover{background-color: rgb(245, 121, 0);color:rgb(255, 255, 255);}")
        self.pushButton_95.setObjectName("pushButton_95")
        self.pushButton_94 = QtWidgets.QPushButton(Dialog)
        self.pushButton_94.setGeometry(QtCore.QRect(90, 130, 51, 61))
        self.pushButton_94.setStyleSheet("QPushButton{border:none;border-radius:8px;background-color: rgb(46, 52, 54);color:rgb(255, 255, 255);}QPushButton:pressed {border:5px}QPushButton:hover{background-color: rgb(245, 121, 0);color:rgb(255, 255, 255);}")
        self.pushButton_94.setObjectName("pushButton_94")
        self.pushButton_100 = QtWidgets.QPushButton(Dialog)
        self.pushButton_100.setGeometry(QtCore.QRect(240, 130, 51, 61))
        self.pushButton_100.setStyleSheet("QPushButton{border:none;border-radius:8px;background-color: rgb(46, 52, 54);color:rgb(255, 255, 255);}QPushButton:pressed {border:5px}QPushButton:hover{background-color: rgb(245, 121, 0);color:rgb(255, 255, 255);}")
        self.pushButton_100.setObjectName("pushButton_100")
        self.pushButton_90 = QtWidgets.QPushButton(Dialog)
        self.pushButton_90.setGeometry(QtCore.QRect(140, 130, 51, 61))
        self.pushButton_90.setStyleSheet("QPushButton{border:none;border-radius:8px;background-color: rgb(46, 52, 54);color:rgb(255, 255, 255);}QPushButton:pressed {border:5px}QPushButton:hover{background-color: rgb(245, 121, 0);color:rgb(255, 255, 255);}")
        self.pushButton_90.setObjectName("pushButton_90")
        self.pushButton_96 = QtWidgets.QPushButton(Dialog)
        self.pushButton_96.setGeometry(QtCore.QRect(540, 130, 51, 61))
        self.pushButton_96.setStyleSheet("QPushButton{border:none;border-radius:8px;background-color: rgb(46, 52, 54);color:rgb(255, 255, 255);}QPushButton:pressed {border:5px}QPushButton:hover{background-color: rgb(245, 121, 0);color:rgb(255, 255, 255);}")
        self.pushButton_96.setObjectName("pushButton_96")
        self.pushButton_92 = QtWidgets.QPushButton(Dialog)
        self.pushButton_92.setGeometry(QtCore.QRect(390, 130, 51, 61))
        self.pushButton_92.setStyleSheet("QPushButton{\n"
"    font: 20pt;\n"
"border:none;\n"
"border-radius:8px;\n"
"background-color: rgb(46, 52, 54);\n"
"color:rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    \n"
"    \n"
"    border:5px\n"
"}\n"
"QPushButton:hover{\n"
"   background-color: rgb(245, 121, 0);\n"
"    color:rgb(255, 255, 255);\n"
"}")
        self.pushButton_92.setObjectName("pushButton_92")
        self.pushButton_93 = QtWidgets.QPushButton(Dialog)
        self.pushButton_93.setGeometry(QtCore.QRect(290, 130, 51, 61))
        self.pushButton_93.setStyleSheet("QPushButton{border:none;border-radius:8px;background-color: rgb(46, 52, 54);color:rgb(255, 255, 255);}QPushButton:pressed {border:5px}QPushButton:hover{background-color: rgb(245, 121, 0);color:rgb(255, 255, 255);}")
        self.pushButton_93.setObjectName("pushButton_93")
        self.pushButton_97 = QtWidgets.QPushButton(Dialog)
        self.pushButton_97.setGeometry(QtCore.QRect(690, 130, 51, 61))
        self.pushButton_97.setStyleSheet("QPushButton{border:none;border-radius:8px;background-color: rgb(46, 52, 54);color:rgb(255, 255, 255);}QPushButton:pressed {border:5px}QPushButton:hover{background-color: rgb(245, 121, 0);color:rgb(255, 255, 255);}")
        self.pushButton_97.setObjectName("pushButton_97")
        self.pushButton_98 = QtWidgets.QPushButton(Dialog)
        self.pushButton_98.setGeometry(QtCore.QRect(440, 130, 51, 61))
        self.pushButton_98.setStyleSheet("QPushButton{border:none;border-radius:8px;background-color: rgb(46, 52, 54);color:rgb(255, 255, 255);}QPushButton:pressed {border:5px}QPushButton:hover{background-color: rgb(245, 121, 0);color:rgb(255, 255, 255);}")
        self.pushButton_98.setObjectName("pushButton_98")
        self.pushButton_88 = QtWidgets.QPushButton(Dialog)
        self.pushButton_88.setGeometry(QtCore.QRect(40, 130, 51, 61))
        self.pushButton_88.setStyleSheet("QPushButton{border:none;border-radius:8px;background-color: rgb(46, 52, 54);color:rgb(255, 255, 255);}QPushButton:pressed {border:5px}QPushButton:hover{background-color: rgb(245, 121, 0);color:rgb(255, 255, 255);}")
        self.pushButton_88.setObjectName("pushButton_88")
        self.pushButton_91 = QtWidgets.QPushButton(Dialog)
        self.pushButton_91.setGeometry(QtCore.QRect(190, 130, 51, 61))
        self.pushButton_91.setStyleSheet("QPushButton{border:none;border-radius:8px;background-color: rgb(46, 52, 54);color:rgb(255, 255, 255);}QPushButton:pressed {border:5px}QPushButton:hover{background-color: rgb(245, 121, 0);color:rgb(255, 255, 255);}")
        self.pushButton_91.setObjectName("pushButton_91")
        self.pushButton_99 = QtWidgets.QPushButton(Dialog)
        self.pushButton_99.setGeometry(QtCore.QRect(590, 130, 51, 61))
        self.pushButton_99.setStyleSheet("QPushButton{border:none;border-radius:8px;background-color: rgb(46, 52, 54);color:rgb(255, 255, 255);}QPushButton:pressed {border:5px}QPushButton:hover{background-color: rgb(245, 121, 0);color:rgb(255, 255, 255);}")
        self.pushButton_99.setObjectName("pushButton_99")
        self.pushButton_101 = QtWidgets.QPushButton(Dialog)
        self.pushButton_101.setGeometry(QtCore.QRect(640, 130, 51, 61))
        self.pushButton_101.setStyleSheet("QPushButton{border:none;border-radius:8px;background-color: rgb(46, 52, 54);color:rgb(255, 255, 255);}QPushButton:pressed {border:5px}QPushButton:hover{background-color: rgb(245, 121, 0);color:rgb(255, 255, 255);}")
        self.pushButton_101.setObjectName("pushButton_101")
        self.pushButton_103 = QtWidgets.QPushButton(Dialog)
        self.pushButton_103.setGeometry(QtCore.QRect(740, 130, 61, 61))
        self.pushButton_103.setStyleSheet("QPushButton{border:none;border-radius:8px;background-color: rgb(46, 52, 54);color:rgb(255, 255, 255);}QPushButton:pressed {border:5px}QPushButton:hover{background-color: rgb(245, 121, 0);color:rgb(255, 255, 255);}")
        self.pushButton_103.setObjectName("pushButton_103")
        self.pushButton_104 = QtWidgets.QPushButton(Dialog)
        self.pushButton_104.setGeometry(QtCore.QRect(350, 190, 51, 61))
        self.pushButton_104.setStyleSheet("QPushButton{border:none;border-radius:8px;background-color: rgb(46, 52, 54);color:rgb(255, 255, 255);}QPushButton:pressed {border:5px}QPushButton:hover{background-color: rgb(245, 121, 0);color:rgb(255, 255, 255);}")
        self.pushButton_104.setObjectName("pushButton_104")
        self.pushButton_105 = QtWidgets.QPushButton(Dialog)
        self.pushButton_105.setGeometry(QtCore.QRect(500, 190, 51, 61))
        self.pushButton_105.setStyleSheet("QPushButton{border:none;border-radius:8px;background-color: rgb(46, 52, 54);color:rgb(255, 255, 255);}QPushButton:pressed {border:5px}QPushButton:hover{background-color: rgb(245, 121, 0);color:rgb(255, 255, 255);}")
        self.pushButton_105.setObjectName("pushButton_105")
        self.pushButton_106 = QtWidgets.QPushButton(Dialog)
        self.pushButton_106.setGeometry(QtCore.QRect(0, 190, 50, 61))
        self.pushButton_106.setStyleSheet("QPushButton{border:none;border-radius:8px;background-color: rgb(46, 52, 54);color:rgb(255, 255, 255);}QPushButton:pressed {border:5px}QPushButton:hover{background-color: rgb(245, 121, 0);color:rgb(255, 255, 255);}")
        self.pushButton_106.setObjectName("pushButton_106")
        self.pushButton_107 = QtWidgets.QPushButton(Dialog)
        self.pushButton_107.setGeometry(QtCore.QRect(100, 190, 51, 61))
        self.pushButton_107.setStyleSheet("QPushButton{border:none;border-radius:8px;background-color: rgb(46, 52, 54);color:rgb(255, 255, 255);}QPushButton:pressed {border:5px}QPushButton:hover{background-color: rgb(245, 121, 0);color:rgb(255, 255, 255);}")
        self.pushButton_107.setObjectName("pushButton_107")
        self.pushButton_108 = QtWidgets.QPushButton(Dialog)
        self.pushButton_108.setGeometry(QtCore.QRect(250, 190, 51, 61))
        self.pushButton_108.setStyleSheet("QPushButton{border:none;border-radius:8px;background-color: rgb(46, 52, 54);color:rgb(255, 255, 255);}QPushButton:pressed {border:5px}QPushButton:hover{background-color: rgb(245, 121, 0);color:rgb(255, 255, 255);}")
        self.pushButton_108.setObjectName("pushButton_108")
        self.pushButton_109 = QtWidgets.QPushButton(Dialog)
        self.pushButton_109.setGeometry(QtCore.QRect(150, 190, 51, 61))
        self.pushButton_109.setStyleSheet("QPushButton{border:none;border-radius:8px;background-color: rgb(46, 52, 54);color:rgb(255, 255, 255);}QPushButton:pressed {border:5px}QPushButton:hover{background-color: rgb(245, 121, 0);color:rgb(255, 255, 255);}")
        self.pushButton_109.setObjectName("pushButton_109")
        self.pushButton_110 = QtWidgets.QPushButton(Dialog)
        self.pushButton_110.setGeometry(QtCore.QRect(550, 190, 51, 61))
        self.pushButton_110.setStyleSheet("QPushButton{border:none;border-radius:8px;background-color: rgb(46, 52, 54);color:rgb(255, 255, 255);}QPushButton:pressed {border:5px}QPushButton:hover{background-color: rgb(245, 121, 0);color:rgb(255, 255, 255);}")
        self.pushButton_110.setObjectName("pushButton_110")
        self.pushButton_111 = QtWidgets.QPushButton(Dialog)
        self.pushButton_111.setGeometry(QtCore.QRect(400, 190, 51, 61))
        self.pushButton_111.setStyleSheet("QPushButton{border:none;border-radius:8px;background-color: rgb(46, 52, 54);color:rgb(255, 255, 255);}QPushButton:pressed {border:5px}QPushButton:hover{background-color: rgb(245, 121, 0);color:rgb(255, 255, 255);}")
        self.pushButton_111.setObjectName("pushButton_111")
        self.pushButton_112 = QtWidgets.QPushButton(Dialog)
        self.pushButton_112.setGeometry(QtCore.QRect(300, 190, 51, 61))
        self.pushButton_112.setStyleSheet("QPushButton{border:none;border-radius:8px;background-color: rgb(46, 52, 54);color:rgb(255, 255, 255);}QPushButton:pressed {border:5px}QPushButton:hover{background-color: rgb(245, 121, 0);color:rgb(255, 255, 255);}")
        self.pushButton_112.setObjectName("pushButton_112")
        self.pushButton_114 = QtWidgets.QPushButton(Dialog)
        self.pushButton_114.setGeometry(QtCore.QRect(450, 190, 51, 61))
        self.pushButton_114.setStyleSheet("QPushButton{border:none;border-radius:8px;background-color: rgb(46, 52, 54);color:rgb(255, 255, 255);}QPushButton:pressed {border:5px}QPushButton:hover{background-color: rgb(245, 121, 0);color:rgb(255, 255, 255);}")
        self.pushButton_114.setObjectName("pushButton_114")
        self.pushButton_115 = QtWidgets.QPushButton(Dialog)
        self.pushButton_115.setGeometry(QtCore.QRect(50, 190, 51, 61))
        self.pushButton_115.setStyleSheet("QPushButton{border:none;border-radius:8px;background-color: rgb(46, 52, 54);color:rgb(255, 255, 255);}QPushButton:pressed {border:5px}QPushButton:hover{background-color: rgb(245, 121, 0);color:rgb(255, 255, 255);}")
        self.pushButton_115.setObjectName("pushButton_115")
        self.pushButton_116 = QtWidgets.QPushButton(Dialog)
        self.pushButton_116.setGeometry(QtCore.QRect(200, 190, 51, 61))
        self.pushButton_116.setStyleSheet("QPushButton{border:none;border-radius:8px;background-color: rgb(46, 52, 54);color:rgb(255, 255, 255);}QPushButton:pressed {border:5px}QPushButton:hover{background-color: rgb(245, 121, 0);color:rgb(255, 255, 255);}")
        self.pushButton_116.setObjectName("pushButton_116")
        self.pushButton_117 = QtWidgets.QPushButton(Dialog)
        self.pushButton_117.setGeometry(QtCore.QRect(600, 190, 51, 61))
        self.pushButton_117.setStyleSheet("QPushButton{border:none;border-radius:8px;background-color: rgb(46, 52, 54);color:rgb(255, 255, 255);}QPushButton:pressed {border:5px}QPushButton:hover{background-color: rgb(245, 121, 0);color:rgb(255, 255, 255);}")
        self.pushButton_117.setObjectName("pushButton_117")
        self.pushButton_118 = QtWidgets.QPushButton(Dialog)
        self.pushButton_118.setGeometry(QtCore.QRect(650, 190, 51, 61))
        self.pushButton_118.setStyleSheet("QPushButton{border:none;border-radius:8px;background-color: rgb(46, 52, 54);color:rgb(255, 255, 255);}QPushButton:pressed {border:5px}QPushButton:hover{background-color: rgb(245, 121, 0);color:rgb(255, 255, 255);}")
        self.pushButton_118.setObjectName("pushButton_118")
        self.pushButton_119 = QtWidgets.QPushButton(Dialog)
        self.pushButton_119.setGeometry(QtCore.QRect(700, 190, 51, 61))
        self.pushButton_119.setStyleSheet("QPushButton{border:none;border-radius:8px;background-color: rgb(46, 52, 54);color:rgb(255, 255, 255);}QPushButton:pressed {border:5px}QPushButton:hover{background-color: rgb(245, 121, 0);color:rgb(255, 255, 255);}")
        self.pushButton_119.setObjectName("pushButton_119")
        self.pushButton_120 = QtWidgets.QPushButton(Dialog)
        self.pushButton_120.setGeometry(QtCore.QRect(750, 190, 51, 61))
        self.pushButton_120.setStyleSheet("QPushButton{border:none;border-radius:8px;background-color: rgb(46, 52, 54);color:rgb(255, 255, 255);}QPushButton:pressed {border:5px}QPushButton:hover{background-color: rgb(245, 121, 0);color:rgb(255, 255, 255);}")
        self.pushButton_120.setObjectName("pushButton_120")
        self.pushButton_55 = QtWidgets.QPushButton(Dialog)
        self.pushButton_55.setGeometry(QtCore.QRect(-150, 370, 51, 61))
        self.pushButton_55.setObjectName("pushButton_55")
        self.pushButton_52 = QtWidgets.QPushButton(Dialog)
        self.pushButton_52.setGeometry(QtCore.QRect(350, 430, 50, 61))
        self.pushButton_52.setStyleSheet("QPushButton{border:none;border-radius:8px;background-color: rgb(46, 52, 54);color:rgb(255, 255, 255);}QPushButton:pressed {border:5px}QPushButton:hover{background-color: rgb(245, 121, 0);color:rgb(255, 255, 255);}")
        self.pushButton_52.setObjectName("pushButton_52")
        self.pushButton_62 = QtWidgets.QPushButton(Dialog)
        self.pushButton_62.setGeometry(QtCore.QRect(400, 250, 51, 61))
        self.pushButton_62.setStyleSheet("QPushButton{border:none;border-radius:8px;background-color: rgb(46, 52, 54);color:rgb(255, 255, 255);}QPushButton:pressed {border:5px}QPushButton:hover{background-color: rgb(245, 121, 0);color:rgb(255, 255, 255);}")
        self.pushButton_62.setObjectName("pushButton_62")
        self.pushButton_60 = QtWidgets.QPushButton(Dialog)
        self.pushButton_60.setGeometry(QtCore.QRect(300, 250, 51, 61))
        self.pushButton_60.setStyleSheet("QPushButton{border:none;border-radius:8px;background-color: rgb(46, 52, 54);color:rgb(255, 255, 255);}QPushButton:pressed {border:5px}QPushButton:hover{background-color: rgb(245, 121, 0);color:rgb(255, 255, 255);}")
        self.pushButton_60.setObjectName("pushButton_60")
        self.pushButton_69 = QtWidgets.QPushButton(Dialog)
        self.pushButton_69.setGeometry(QtCore.QRect(350, 250, 51, 61))
        self.pushButton_69.setStyleSheet("QPushButton{border:none;border-radius:8px;background-color: rgb(46, 52, 54);color:rgb(255, 255, 255);}QPushButton:pressed {border:5px}QPushButton:hover{background-color: rgb(245, 121, 0);color:rgb(255, 255, 255);}")
        self.pushButton_69.setObjectName("pushButton_69")
        self.pushButton_63 = QtWidgets.QPushButton(Dialog)
        self.pushButton_63.setGeometry(QtCore.QRect(350, 310, 51, 61))
        self.pushButton_63.setStyleSheet("QPushButton{border:none;border-radius:8px;background-color: rgb(46, 52, 54);color:rgb(255, 255, 255);}QPushButton:pressed {border:5px}QPushButton:hover{background-color: rgb(245, 121, 0);color:rgb(255, 255, 255);}")
        self.pushButton_63.setObjectName("pushButton_63")
        self.pushButton_65 = QtWidgets.QPushButton(Dialog)
        self.pushButton_65.setGeometry(QtCore.QRect(300, 310, 51, 61))
        self.pushButton_65.setStyleSheet("QPushButton{border:none;border-radius:8px;background-color: rgb(46, 52, 54);color:rgb(255, 255, 255);}QPushButton:pressed {border:5px}QPushButton:hover{background-color: rgb(245, 121, 0);color:rgb(255, 255, 255);}")
        self.pushButton_65.setObjectName("pushButton_65")
        self.pushButton_64 = QtWidgets.QPushButton(Dialog)
        self.pushButton_64.setGeometry(QtCore.QRect(400, 310, 51, 61))
        self.pushButton_64.setStyleSheet("QPushButton{border:none;border-radius:8px;background-color: rgb(46, 52, 54);color:rgb(255, 255, 255);}QPushButton:pressed {border:5px}QPushButton:hover{background-color: rgb(245, 121, 0);color:rgb(255, 255, 255);}")
        self.pushButton_64.setObjectName("pushButton_64")
        self.pushButton_58 = QtWidgets.QPushButton(Dialog)
        self.pushButton_58.setGeometry(QtCore.QRect(300, 370, 51, 61))
        self.pushButton_58.setStyleSheet("QPushButton{border:none;border-radius:8px;background-color: rgb(46, 52, 54);color:rgb(255, 255, 255);}QPushButton:pressed {border:5px}QPushButton:hover{background-color: rgb(245, 121, 0);color:rgb(255, 255, 255);}")
        self.pushButton_58.setObjectName("pushButton_58")
        self.pushButton_67 = QtWidgets.QPushButton(Dialog)
        self.pushButton_67.setGeometry(QtCore.QRect(350, 370, 50, 61))
        self.pushButton_67.setStyleSheet("QPushButton{border:none;border-radius:8px;background-color: rgb(46, 52, 54);color:rgb(255, 255, 255);}QPushButton:pressed {border:5px}QPushButton:hover{background-color: rgb(245, 121, 0);color:rgb(255, 255, 255);}")
        self.pushButton_67.setObjectName("pushButton_67")
        self.pushButton_54 = QtWidgets.QPushButton(Dialog)
        self.pushButton_54.setGeometry(QtCore.QRect(400, 370, 50, 61))
        self.pushButton_54.setStyleSheet("QPushButton{border:none;border-radius:8px;background-color: rgb(46, 52, 54);color:rgb(255, 255, 255);}QPushButton:pressed {border:5px}QPushButton:hover{background-color: rgb(245, 121, 0);color:rgb(255, 255, 255);}")
        self.pushButton_54.setObjectName("pushButton_54")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "virtual keyboard"))
        self.pushButton.setText(_translate("Dialog", "~"))
        self.pushButton_2.setText(_translate("Dialog", "!"))
        self.pushButton_3.setText(_translate("Dialog", "@"))
        self.pushButton_4.setText(_translate("Dialog", "#"))
        self.pushButton_5.setText(_translate("Dialog", "$"))
        self.pushButton_6.setText(_translate("Dialog", "%"))
        self.pushButton_7.setText(_translate("Dialog", "^"))
        self.pushButton_8.setText(_translate("Dialog", "and"))
        self.pushButton_9.setText(_translate("Dialog", "*"))
        self.pushButton_10.setText(_translate("Dialog", "("))
        self.pushButton_11.setText(_translate("Dialog", ")"))
        self.pushButton_12.setText(_translate("Dialog", "_"))
        self.pushButton_13.setText(_translate("Dialog", "+"))
        self.pushButton_14.setText(_translate("Dialog", "/"))
        self.pushButton_15.setText(_translate("Dialog", "backspace"))
        self.pushButton_16.setText(_translate("Dialog", "-"))
        self.pushButton_17.setText(_translate("Dialog", "tab"))
        self.pushButton_18.setText(_translate("Dialog", "q"))
        self.pushButton_19.setText(_translate("Dialog", "w"))
        self.pushButton_20.setText(_translate("Dialog", "e"))
        self.pushButton_21.setText(_translate("Dialog", "r"))
        self.pushButton_22.setText(_translate("Dialog", "t"))
        self.pushButton_23.setText(_translate("Dialog", "y"))
        self.pushButton_24.setText(_translate("Dialog", "u"))
        self.pushButton_25.setText(_translate("Dialog", "i"))
        self.pushButton_26.setText(_translate("Dialog", "o"))
        self.pushButton_27.setText(_translate("Dialog", "p"))
        self.pushButton_28.setText(_translate("Dialog", "["))
        self.pushButton_29.setText(_translate("Dialog", "]"))
        self.pushButton_30.setText(_translate("Dialog", "\\"))
        self.pushButton_31.setText(_translate("Dialog", "{"))
        self.pushButton_32.setText(_translate("Dialog", "}"))
        self.pushButton_33.setText(_translate("Dialog", "+"))
        self.pushButton_102.setText(_translate("Dialog", "j"))
        self.pushButton_89.setText(_translate("Dialog", ";"))
        self.pushButton_95.setText(_translate("Dialog", "caps"))
        self.pushButton_94.setText(_translate("Dialog", "s"))
        self.pushButton_100.setText(_translate("Dialog", "g"))
        self.pushButton_90.setText(_translate("Dialog", "d"))
        self.pushButton_96.setText(_translate("Dialog", "\'"))
        self.pushButton_92.setText(_translate("Dialog", "k"))
        self.pushButton_93.setText(_translate("Dialog", "h"))
        self.pushButton_97.setText(_translate("Dialog", "\""))
        self.pushButton_98.setText(_translate("Dialog", "l"))
        self.pushButton_88.setText(_translate("Dialog", "a"))
        self.pushButton_91.setText(_translate("Dialog", "f"))
        self.pushButton_99.setText(_translate("Dialog", "enter"))
        self.pushButton_101.setText(_translate("Dialog", ":"))
        self.pushButton_103.setText(_translate("Dialog", "numlock"))
        self.pushButton_104.setText(_translate("Dialog", "m"))
        self.pushButton_105.setText(_translate("Dialog", "?"))
        self.pushButton_106.setText(_translate("Dialog", "shift"))
        self.pushButton_107.setText(_translate("Dialog", "x"))
        self.pushButton_108.setText(_translate("Dialog", "b"))
        self.pushButton_109.setText(_translate("Dialog", "c"))
        self.pushButton_110.setText(_translate("Dialog", "<"))
        self.pushButton_111.setText(_translate("Dialog", ","))
        self.pushButton_112.setText(_translate("Dialog", "n"))
        self.pushButton_114.setText(_translate("Dialog", "."))
        self.pushButton_115.setText(_translate("Dialog", "z"))
        self.pushButton_116.setText(_translate("Dialog", "v"))
        self.pushButton_117.setText(_translate("Dialog", ">"))
        self.pushButton_118.setText(_translate("Dialog", "fn"))
        self.pushButton_119.setText(_translate("Dialog", "ctrl"))
        self.pushButton_120.setText(_translate("Dialog", "windo"))
        self.pushButton_55.setText(_translate("Dialog", "4"))
        self.pushButton_52.setText(_translate("Dialog", "0"))
        self.pushButton_62.setText(_translate("Dialog", "3"))
        self.pushButton_60.setText(_translate("Dialog", "1"))
        self.pushButton_69.setText(_translate("Dialog", "2"))
        self.pushButton_63.setText(_translate("Dialog", "5"))
        self.pushButton_65.setText(_translate("Dialog", "4"))
        self.pushButton_64.setText(_translate("Dialog", "6"))
        self.pushButton_58.setText(_translate("Dialog", "7"))
        self.pushButton_67.setText(_translate("Dialog", "8"))
        self.pushButton_54.setText(_translate("Dialog", "9"))
	
        self.pushButton.clicked.connect(lambda: self.butt_click(self.pushButton_1))
        self.pushButton_2.clicked.connect(lambda: self.butt_click(self.pushButton_2))
        self.pushButton_3.clicked.connect(lambda: self.butt_click(self.pushButton_3))
        self.pushButton_4.clicked.connect(lambda: self.butt_click(self.pushButton_4))
        self.pushButton_5.clicked.connect(lambda: self.butt_click(self.pushButton_5))
        self.pushButton_6.clicked.connect(lambda: self.butt_click(self.pushButton_6))
        self.pushButton_7.clicked.connect(lambda: self.butt_click(self.pushButton_7))
        self.pushButton_8.clicked.connect(lambda: self.butt_click(self.pushButton_8))
        self.pushButton_9.clicked.connect(lambda: self.butt_click(self.pushButton_9))
        self.pushButton_10.clicked.connect(lambda: self.butt_click(self.pushButton_10))
        self.pushButton_11.clicked.connect(lambda: self.butt_click(self.pushButton_11))
        self.pushButton_12.clicked.connect(lambda: self.butt_click(self.pushButton_12))
        self.pushButton_13.clicked.connect(lambda: self.butt_click(self.pushButton_13))
        self.pushButton_14.clicked.connect(lambda: self.butt_click(self.pushButton_14))
        self.pushButton_15.clicked.connect(lambda: self.butt_click(self.pushButton_15))
        self.pushButton_16.clicked.connect(lambda: self.butt_click(self.pushButton_16))
        self.pushButton_17.clicked.connect(lambda: self.butt_click(self.pushButton_17))
        self.pushButton_18.clicked.connect(lambda: self.butt_click(self.pushButton_18))
        self.pushButton_19.clicked.connect(lambda: self.butt_click(self.pushButton_19))
        self.pushButton_20.clicked.connect(lambda: self.butt_click(self.pushButton_20))
        self.pushButton_21.clicked.connect(lambda: self.butt_click(self.pushButton_21))
        self.pushButton_22.clicked.connect(lambda: self.butt_click(self.pushButton_22))
        self.pushButton_23.clicked.connect(lambda: self.butt_click(self.pushButton_23))
        self.pushButton_24.clicked.connect(lambda: self.butt_click(self.pushButton_24))
        self.pushButton_25.clicked.connect(lambda: self.butt_click(self.pushButton_25))
        self.pushButton_26.clicked.connect(lambda: self.butt_click(self.pushButton_26))
        self.pushButton_27.clicked.connect(lambda: self.butt_click(self.pushButton_27))
        self.pushButton_28.clicked.connect(lambda: self.butt_click(self.pushButton_28))
        self.pushButton_29.clicked.connect(lambda: self.butt_click(self.pushButton_29))
        self.pushButton_30.clicked.connect(lambda: self.butt_click(self.pushButton_30))
        self.pushButton_31.clicked.connect(lambda: self.butt_click(self.pushButton_31))
        self.pushButton_32.clicked.connect(lambda: self.butt_click(self.pushButton_32))
        self.pushButton_33.clicked.connect(lambda: self.butt_click(self.pushButton_33))
        self.pushButton_102.clicked.connect(lambda: self.butt_click(self.pushButton_102))
        self.pushButton_89.clicked.connect(lambda: self.butt_click(self.pushButton_89))
        self.pushButton_95.clicked.connect(lambda: self.butt_click(self.pushButton_95))
        self.pushButton_94.clicked.connect(lambda: self.butt_click(self.pushButton_94))
        self.pushButton_100.clicked.connect(lambda: self.butt_click(self.pushButton_100))
        self.pushButton_90.clicked.connect(lambda: self.butt_click(self.pushButton_90))
        self.pushButton_96.clicked.connect(lambda: self.butt_click(self.pushButton_96))
        self.pushButton_92.clicked.connect(lambda: self.butt_click(self.pushButton_92))
        self.pushButton_93.clicked.connect(lambda: self.butt_click(self.pushButton_93))
        self.pushButton_97.clicked.connect(lambda: self.butt_click(self.pushButton_97))
        self.pushButton_98.clicked.connect(lambda: self.butt_click(self.pushButton_98))
        self.pushButton_88.clicked.connect(lambda: self.butt_click(self.pushButton_88))
        self.pushButton_91.clicked.connect(lambda: self.butt_click(self.pushButton_91))
        self.pushButton_99.clicked.connect(lambda: self.butt_click(self.pushButton_99))
        self.pushButton_101.clicked.connect(lambda: self.butt_click(self.pushButton_101))
        self.pushButton_103.clicked.connect(lambda: self.butt_click(self.pushButton_103))
        self.pushButton_104.clicked.connect(lambda: self.butt_click(self.pushButton_104))
        self.pushButton_105.clicked.connect(lambda: self.butt_click(self.pushButton_105))
        self.pushButton_106.clicked.connect(lambda: self.butt_click(self.pushButton_106))
        self.pushButton_107.clicked.connect(lambda: self.butt_click(self.pushButton_107))
        self.pushButton_108.clicked.connect(lambda: self.butt_click(self.pushButton_108))
        self.pushButton_109.clicked.connect(lambda: self.butt_click(self.pushButton_109))
        self.pushButton_110.clicked.connect(lambda: self.butt_click(self.pushButton_110))
        self.pushButton_111.clicked.connect(lambda: self.butt_click(self.pushButton_111))
        self.pushButton_112.clicked.connect(lambda: self.butt_click(self.pushButton_112))
        self.pushButton_114.clicked.connect(lambda: self.butt_click(self.pushButton_114))
        self.pushButton_115.clicked.connect(lambda: self.butt_click(self.pushButton_115))
        self.pushButton_116.clicked.connect(lambda: self.butt_click(self.pushButton_116))
        self.pushButton_117.clicked.connect(lambda: self.butt_click(self.pushButton_117))
        self.pushButton_118.clicked.connect(lambda: self.butt_click(self.pushButton_118))
        self.pushButton_119.clicked.connect(lambda: self.butt_click(self.pushButton_119))
        self.pushButton_120.clicked.connect(lambda: self.butt_click(self.pushButton_120))
        self.pushButton_55.clicked.connect(lambda: self.butt_click(self.pushButton_55))
        self.pushButton_52.clicked.connect(lambda: self.butt_click(self.pushButton_52))
        self.pushButton_62.clicked.connect(lambda: self.butt_click(self.pushButton_62))
        self.pushButton_60.clicked.connect(lambda: self.butt_click(self.pushButton_60))
        self.pushButton_69.clicked.connect(lambda: self.butt_click(self.pushButton_69))
        self.pushButton_63.clicked.connect(lambda: self.butt_click(self.pushButton_63))
        self.pushButton_65.clicked.connect(lambda: self.butt_click(self.pushButton_65))
        self.pushButton_64.clicked.connect(lambda: self.butt_click(self.pushButton_64))
        self.pushButton_58.clicked.connect(lambda: self.butt_click(self.pushButton_58))
        self.pushButton_67.clicked.connect(lambda: self.butt_click(self.pushButton_67))
        self.pushButton_54.clicked.connect(lambda: self.butt_click(self.pushButton_54))

    def butt_click(self,b) :
        print (b.text())
        		
	
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

